# Generated by Django 4.2.30 on 2026-06-21 02:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('user', '使用者')], default='user', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='柜格编号')),
                ('size', models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], default='medium', max_length=20, verbose_name='尺寸')),
                ('status', models.CharField(choices=[('available', '可预约'), ('reserved', '已预约'), ('in_use', '使用中'), ('pending_clean', '待清理'), ('paused', '暂停开放')], default='available', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '柜格',
                'verbose_name_plural': '柜格',
                'db_table': 'locker',
                'ordering': ['locker_group', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LockerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='柜组名称')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '柜组',
                'verbose_name_plural': '柜组',
                'db_table': 'locker_group',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='预约开始时间')),
                ('end_time', models.DateTimeField(verbose_name='预约结束时间')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='使用用途')),
                ('status', models.CharField(choices=[('pending', '待使用'), ('active', '使用中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='预约状态')),
                ('cleaned', models.BooleanField(default=False, verbose_name='是否已清理')),
                ('cleaned_at', models.DateTimeField(blank=True, null=True, verbose_name='清理时间')),
                ('clean_note', models.TextField(blank=True, null=True, verbose_name='清理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cleaned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_reservations', to=settings.AUTH_USER_MODEL, verbose_name='清理人')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='locker_api.locker', verbose_name='柜格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'db_table': 'reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='locker',
            name='locker_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='locker_api.lockergroup', verbose_name='柜组'),
        ),
    ]
