# Generated by Django 4.2.30 on 2026-06-21 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_end_time', models.DateTimeField(verbose_name='原结束时间')),
                ('requested_end_time', models.DateTimeField(verbose_name='期望结束时间')),
                ('reason', models.TextField(verbose_name='申请原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审批状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='审批备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_applications', to='locker_api.reservation', verbose_name='原预约')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_renewals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '续期申请',
                'verbose_name_plural': '续期申请',
                'db_table': 'renewal_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
