# Generated by Django 4.2.16 on 2026-06-21 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker_api', '0002_renewalapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='change_count',
            field=models.IntegerField(default=0, verbose_name='改签次数'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_changed',
            field=models.BooleanField(default=False, verbose_name='是否改签过'),
        ),
        migrations.CreateModel(
            name='ReservationChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('time', '修改时间'), ('locker', '更换柜格'), ('both', '修改时间并更换柜格')], max_length=20, verbose_name='改签类型')),
                ('original_locker_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='原柜格编号')),
                ('new_locker_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='新柜格编号')),
                ('original_start_time', models.DateTimeField(verbose_name='原开始时间')),
                ('original_end_time', models.DateTimeField(verbose_name='原结束时间')),
                ('new_start_time', models.DateTimeField(verbose_name='新开始时间')),
                ('new_end_time', models.DateTimeField(verbose_name='新结束时间')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='改签原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='改签时间')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_changes', to=settings.AUTH_USER_MODEL, verbose_name='改签人')),
                ('new_locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locker_api.locker', verbose_name='新柜格')),
                ('original_locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locker_api.locker', verbose_name='原柜格')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_histories', to='locker_api.reservation', verbose_name='预约记录')),
            ],
            options={
                'verbose_name': '预约改签记录',
                'verbose_name_plural': '预约改签记录',
                'db_table': 'reservation_change_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
